{% set version = "2.1.0" %}

package:
  name: munch
  version: {{ version }}

source:
  fn: munch-{{ version }}.tar.gz
  url: https://github.com/Infinidat/munch/archive/{{ version }}.tar.gz
  sha256: b922be9ecfe51ef2cb6a15905c4eeca13540dace2e5324bbb15b54efdf7dd60f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - munch

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  license_file: LICENSE.txt
  summary: 'A dot-accessible dictionary (a la JavaScript objects).'

extra:
  recipe-maintainers:
    - ocefpaf
