{% set name = "munch" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 542cb151461263216a4e37c3fd9afc425feeaf38aaa3025cd2a981fadb422235

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools >=61
    - pbr >=3.0
  run:
    - python
    - importlib_metadata >=1.7.0  # [py<38]

test:
  source_files:
    - tests
    - README.md
  imports:
    - munch
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - astroid >=2.0

about:
  home: https://github.com/Infinidat/munch
  summary: 'A dot-accessible dictionary (a la JavaScript objects)'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    munch is a fork of David Schoonover's Bunch package, providing similar functionality.
    99% of the work was done by him, and the fork was made mainly for lack of responsiveness
    for fixes and maintenance on the original code.
  dev_url: https://github.com/Infinidat/munch
  doc_url: https://github.com/Infinidat/munch/blob/develop/README.md

extra:
  recipe-maintainers:
    - ocefpaf
  skip-lints:
    - host_section_needs_exact_pinnings
