{% set version = "2.1.1" %}

package:
  name: munch
  version: {{ version }}

source:
  fn: munch-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/munch/munch-{{ version }}.tar.gz
  sha256: 648b650d1eb0173bd83c29f2eea2568b7591c1e05c87971387d170c71c6397e8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - munch

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  license_file: LICENSE.txt
  summary: 'A dot-accessible dictionary (a la JavaScript objects).'

extra:
  recipe-maintainers:
    - ocefpaf
