{% set version = "2.5.0" %}

package:
  name: munch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/munch/munch-{{ version }}.tar.gz
  sha256: 2d735f6f24d4dba3417fa448cae40c6e896ec1fdab6cdb5e6510999758a4dbd2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=17.1
    - pbr >=3.0
  run:
    - python
    - setuptools >=17.1
    - six

test:
  imports:
    - munch

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  license_file: LICENSE.txt
  summary: 'A dot-accessible dictionary (a la JavaScript objects)'

extra:
  recipe-maintainers:
    - ocefpaf
