travis:
  secure:
    BINSTAR_TOKEN: JeJyYwYkjNVrGV3SJRGrZljHghlanuc19RrjjmMvhmBkO3XiEYhcFd879GueUq84BbAoWKsAk7bi77oOSOu+aIa5dwTBE4382aWzuY3sIOoass3on0n+FJJymg/a5vErfuL748w6tfRqJu+T4OH1VPU09iPu5xmxn6tbGS7zMUU0NAndn18/5QvUl3b1XJW/BdT7i/7J6EQ1b0/qelkzYVIgTphfBnHDDPRK+Z+I+KMjPPaN25lATkZK79eTKEogv/4SRcup5kBoiX9c2XLl6O/A5rUKu2NKBFQnM3FmuO31OiwKXDWZA/pLmPVtDCVd2J2UY/pgEtC+ZWxO/rPM3d36VqGml5LEhomAfvpETz68DxHS1JdsjNQnIFSmxmen9uBo44EO+LkZcL8XBqdlPKeReTNmAbLvizbn0H3gGMMxShCQj4iR7gq0gBmjeaAjobfOcCCXmQMNrEO1fMWTiN38T9h0owj9GPlQ4OwjQ7mZYCwUqfa9NFs969VlH2dzbuXq0HsNlGONg83y4dGsSXLni+ah/v8bpDPTCKoYt4p8xewzda4nM4QqGrsvQkhWOFAHLnr6KIAlmRwIY41U9AaUf2zOgSB1+mFSHb9z+UKqjNrChooyRpyQXT8KOvM1cdx/tXFvrMwphmeIY92DSKCCeyZKQbMaQ6BD/ehOyhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
