travis:
  secure:
    BINSTAR_TOKEN: fK74lUiNy4AuK4mT+ihBvIQfetO2eo4nO2nYBTcDiTIyigd2Go39JZMcOk1XjzfegFUTENrXFS5De3ntj3IGi2pRQzJRixxApxc3KZSvxbdcm8vK6nZZrtuoSPpLXbQecIwX5Hb9MlAJJbpstfodcEyPKPD4ZIgaV03xi7yP7A9PCPsW2tEfGslMyd2lFhOgw+ISXwjkhYwxB/BTRhCZlEa91pnNpFgXxr/1mcaGb5+iypXX4vXkaReCSvjjBXkVDJXiFI8HcRQFb+xvP23D9GbAuw45VRiOQE9CROv0D46o2/lI7jVdw2+wb6OOAaIHHIkhE8DhI9j3psSDlFBv4vqCFREGDr2Ftr9eAlJu1zv2q7UQiCGFQotgeYjSSp7zSXYYVJfgKWeX0Ikt3EeEgxBfEkSbKYc6K+YWySQdSiOp4WU5EC4zKxrpEC4/qUfm6oyBve0Z2f1Tc9LCRDm/4HdLkm/6/xYjO+Uciryl6OBx6kMG2UIZOa2Nr+sDP8ZyAscAeUQKmKc9DJvFqBc6S07IcPfEKxMpFAbQnLTnlM0PjtXAkScZ7pscebzoFNvY2+/z4HNP/mSNWfLiGA+lcFpRAKeos/z9oYwtFWUoZ5iefe24YAhUbGmWKmNs6SiEV/+55rsRC7h0XCxOt4hgOZmGhE1mZfd8VbS8/rCejxc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
